spring.application.name=lumina
spring.datasource.url=jdbc:postgresql://localhost:5432/lumina
spring.datasource.username=postgres
spring.datasource.password=jrnet1227@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false